src/nitro.ts

Addresses issue #30 
Resolves #30 by replacing the process.env.NUXT_NO_SSR in the nitro config based on the user setting in the Nuxt config. Currently there is a runtime error that fails when `ssr: false`.

fix(nitro): add `NUXT_NO_SSR` when ssr is disabled

---

package.json
yarn.lock

This PR upgrades some safe dependencies and refreshes a lockfile.
closes #342

chore: upgrade some safe dependencies and refresh lockfile

---

package.json
src/runtime/capi.legacy.mjs
test/bridge.test.ts
yarn.lock

this fixes a couple of issues with the Vue 2.7 migration and legacy CAPI support.

fix: update implementation for legacy useFetch for vue 2.7

---

module.cjs
src/module.ts

Currently bridge module runs _last_ (to ensure hooks are registered first) but it should probably normalize the config _first_. This PR adds a stub module to set nuxt context, set `bridge` option, and normalize layers.
Here's an example of a config that now works but previously didn't:
```js
import { defineNuxtConfig } from '@nuxt/bridge'
import { useNuxt } from '@nuxt/kit'
export default defineNuxtConfig({
buildModules: [
function () {
const nuxt = useNuxt()
}
]
})
```

fix: set nuxt context and normalise config as first module

---

src/module.ts

We are performing normalization in `defineNuxtConfig` (e.g. https://github.com/nuxt/bridge/pull/397) and if users don't use it Bridge won't work as expected.

fix: throw error if wrapper isn't used

---

src/nitro.ts

resolves https://github.com/nuxt/bridge/issues/472
Users who want to programmatically determine what routes should be prerendered should use a hook to do so:
```js
import { defineNuxtConfig } from '@nuxt/bridge'
export default defineNuxtConfig({
hooks: {
async 'nitro:config' (config) {
const routes = await getRoutes()
config.prerender.routes.push(...routes)
}
}
})
```
In the mean time, for backward compatibility, we can call the `generate.routes` function.

fix: handle functional `generate.routes`

---

src/nitro.ts

resolves  #499, resolves https://github.com/nuxt/bridge/issues/497
Regression of https://github.com/nuxt/bridge/pull/476 - we were not normalizing the webpack _dev_ manifest.

fix: normalize dev webpack manifest

---

src/nitro.ts

resolves  #490
Although marking `nitroGenerator` as true by default, we were not actually checking the resolved options. This PR also updates the route generation to be based off nitro's prerender options, not the nuxt ones.

fix(nitro): default to nitro generator and use resolved nitro routes

---

playground/layouts/error.vue
src/runtime/app.plugin.mjs

Kind of a `chore` PR.
Resolves both current eslint warnings.
- import `version` from `Vue`
- add type to error prop in playground layout

fix: use named version from 'vue'

---

src/runtime/asyncData.ts
src/runtime/cookie.ts
src/runtime/head/composables.ts
src/runtime/head/vueuse-head.plugin.ts
src/runtime/ssr.ts

This should improve stability of vite implementation and also improve type support somewhat - I was getting hanging in dev mode in a separate PR owing to circular composable references.

fix: improve types and use relative imports for composables

---

src/app.ts
src/runtime/composables.ts
src/runtime/config.plugin.mjs

resolves #458
This adds a plugin to normalize `$config` with a Proxy, moving it from the composable `useRuntimeConfig` into the app itself, which means that usage from `ctx.$config` within plugins works as expected for user plugins.

fix: apply runtimeConfig proxy directly to ctx.config

---

src/runtime/nitro/renderer.ts

https://github.com/nuxt/framework/pull/6042
This aligns Bridge further with current Nuxt 3 nitropack render response handler, including calling `render:html` and using a render handler.

feat: use new nitropack render response

---

playground/nuxt.config.ts
playground/pages/runtime-config.vue
playground/plugins/config.js
src/app.ts
test/bridge.test.ts

previously, module-injected plugins did not have access to normalized config. cc: @aldarund

fix: normalize config before module-injected plugins

---

src/imports/presets.ts
src/runtime/capi.legacy.ts
src/runtime/composables.ts

This reverts commit 5e5fa505163c78f4ffb7ab053a7996977c43caf9.
resolves https://github.com/nuxt/bridge/issues/554, https://github.com/nuxt-modules/color-mode/issues/169
When we switched to using native vue-router composables in https://github.com/nuxt/bridge/pull/533, we lost support for using `useRoute` and `useRouter` in Nuxt plugins, middleware, etc. (ie. anywhere outside of a component). This PR reverts that change in that if called outside a composable it will revert to previous behaviour. However, within a component, we still use the native `vue-router` composable.

fix: provide nuxt `useRoute` and `useRouter` composables

---

src/app.ts
src/imports/module.ts

https://github.com/nuxt/framework/issues/2215
This allows us to invalidate virtual templates when the nuxt 2 watcher detects changes, such as wehn composables are added to the app, and adds compatibility with any future kit plugin to invalidate templates..

fix: hook up watchers to nuxt 3 hooks

---

playground/nuxt.config.ts
playground/pages/route-rules/spa.vue
src/runtime/nitro/renderer.ts
test/bridge.test.ts
types.d.ts

This brings the `ssr` route rule from nuxt 3 to bridge: https://github.com/nuxt/framework/pull/7938

feat: add `ssr` routeRule

---

src/vite/manifest.ts

#580
This fixes entrypoint-legacy not loading any further modules when the production build is started with `NUXT_APP_CDN_URL=https://cdn.url` due to `.slice(1)` mangling the URLs to `ttps://cdn.ur/_nuxt/module.js` (note the missing `h`).
Resolves #580.

fix: regression in entrypoint with CDN URL

---

packages/bridge/src/runtime/composables.ts
playground/pages/navigate-to-external.vue
test/bridge.test.ts

Closes: https://github.com/nuxt/bridge/issues/665
This PR backports `navigateTo` composable from `nuxt/framework` package with Vue2-related types. Extra tests added

feat: backport `navigateTo` updates from v3

---

packages/bridge/src/runtime/composables.ts
playground/pages/navigate-to.vue
playground/pages/navigation-target.vue
test/bridge.test.ts

Resolves https://github.com/nuxt/bridge/issues/681
Quite funny moment: tests was working, because they tested redirect to `/` location, which was the fallback. I've updated the tests to check non-fallback page. I guess we need more to cover.

fix: correct `redirectLocation` path resolution

---

packages/bridge/src/module.ts

Resolves https://github.com/nuxt/bridge/issues/701
Should only be used with Nuxt 2.16+
I was thinking of disabling it by default but as the TODO comment said *remove*, I went with it. Happy to adapt though.

fix: remove postcss8 option

---

README.md
playground/package.json
pnpm-lock.yaml

With the release of 2.16.0, we can move our recommendation for bridge to consume the normal (but latest) 2.x release, with the expectation that any patches we need for bridge can be released in the usual way.

chore: update to recommend 2.16.0 rather than edge channel

---

packages/bridge-schema/package.json
packages/bridge/package.json
packages/bridge/src/head.ts
playground/package.json
pnpm-lock.yaml

https://github.com/nuxt/bridge/issues/708
Updating `@vueuse/head` to v1 requires `unhead` transpile.
(This is because `unhead` uses `optional chaining`.)
The error you are getting with `iron-webcrypto` is not related to `@vueuse/head`, so we have not fixed it.

chore: update devdependency @vueuse/head to v1

---

packages/bridge/src/vite/server.ts

resolves https://github.com/nuxt/bridge/issues/734
After comparing the `.nuxt/dist/server/client.manifest.json` of Nuxt 3 and Nuxt Bridge, I confirmed that the Nuxt 3 side does not include `../`.

fix: remove `../` from css paths

---

packages/bridge/src/runtime/nitro/error.ts
test/bridge.test.ts

https://github.com/nuxt/bridge/issues/631
I have ported the contents of `nitro/error.ts` from Nuxt 3. (I'm not very confident, though.)
By implementing it in the playground as shown below, I was able to confirm that the contents of the headers are not missing.
layouts/error.vue
```vue
<template>
<div>Error page: {{ headers }}</div>
</template>
<script setup>
const { ssrContext } = useNuxtApp()
const headers = useState('headers', () => ssrContext?.req.headers)
</script>
```

feat: update error handler to latest upstream version

---

packages/bridge/src/nitro.ts

In the process of outputting the manifest, other code uses `JSON.stringify(json, null, 2)` to stringify. Therefore, I changed it to match other code by using `JSON.stringify(json, null, 2)`.

refactor: in line with other code, change the indentation to 2 spaces.

---

packages/bridge/src/module.ts

https://github.com/nuxt/bridge/issues/607, https://github.com/nuxt/bridge/issues/620
I will port the devMiddleware settings from Nuxt 3.
https://github.com/nuxt/nuxt/blob/26c653128201526168172da2892aea052c486d1e/packages/webpack/src/webpack.ts#L109-L114
https://github.com/nuxt/bridge/issues/607
Please set it as follows:
```ts
// nuxt.config.ts
export default defineNuxtConfig({
ssr: true,
bridge: {
nitro: true
}
})
```
https://github.com/nuxt/bridge/issues/620
Please set it as follows:
```ts
// nuxt.config.ts
export default defineNuxtConfig({
ssr: false,
bridge: {
nitro: true
}
})
```

fix: add `server:devHandler` hook for webpack

---

packages/bridge/src/vite/manifest.ts

resolves https://github.com/nuxt/bridge/issues/686
In the case of `vite: true` && `ssr: false`, the manifest was not correctly generated, so I have fixed it.

fix: generate vite dev manifest when `ssr: false`

---

packages/bridge-schema/build.config.ts
packages/bridge-schema/src/config/build.ts

Close #784
Add `@type {boolean | typeof import('extract-css-chunks-webpack-plugin').PluginOptions}` in JSDoc and then `unbuild` will generate the correct type.

fix: use correct `extractCSS` type

---

packages/bridge/src/runtime/capi.legacy.ts

Fixes: https://github.com/nuxt/bridge/issues/805
The `legacy capi` message is for developers and users do not need to know this information, so it should not be displayed in production.

fix: do not warn about legacy capi in production

---

packages/bridge/src/runtime/composables.ts
playground/middleware/redirect.ts
playground/pages/navigate-to-external.vue
playground/pages/redirect.vue
test/bridge.test.ts

Fixed `defineNuxtRouteMiddleware` as it needs to be converted to legacy middleware and executed.
Also, `abortNavigation` has been updated with reference to Nuxt 3.

fix: convert `defineNuxtRouteMiddleware` to legacy middleware

---

playground/pages/add-route-middleware.vue
playground/plugins/setup.js
test/bridge.test.ts

I would like to add `addRouteMiddleware` as it was not tested.

feat: add `addRouteMiddleware` test

---

README.md

https://github.com/nuxt/bridge/issues/834
This improves the readme to mention additional steps needed in order to use the `nitro: false` option.
By including usage notes in the `nitro` sample config provided in the readme, this may help people avoid a non-obvious gotcha.
Had these notes been next to the sample Bridge config options, I wouldn't have thought that dev server was broken.
Follows https://github.com/nuxt/bridge/issues/808

docs: update example options in readme to mention using old cli

---

packages/bridge/src/vite/templates.ts

resolve: https://github.com/nuxt/bridge/issues/847
I think this is happening because deleting `storeModules.root` causes `storeModules.root` to be empty when `createStore` is re-run.

fix: do not delete root

---

packages/bridge/src/type-templates.ts

It is more correct to use `Nuxt2Context` for nuxt 2 middleware.

fix: Use `Nuxt2Context` instead of `NuxtAppCompat`.

---

.github/workflows/ci.yml
package.json
packages/bridge/src/imports/module.ts
packages/bridge/src/imports/transform.ts
packages/bridge/test/auto-imports.test.ts

Fixes: https://github.com/nuxt/bridge/issues/870
I have fixed it so that it throws an error if autoImport: false as in Nuxt 3.

fix: do not inject imports within `node_modules`

---

packages/bridge/src/app.ts
packages/bridge/src/head.ts

Fixes: https://github.com/nuxt/bridge/issues/876
This occurs due to the effect of changing the `defineNuxtComponent` to use `useHead` at https://github.com/nuxt/bridge/pull/838.
Now it is only transpiled if meta: other than false, so meta: false will result in a build error.
I think that to enable bridge.head, bridge.app also needs to be enabled, so I moved it into `setupAppBridge`.

fix: transpile unhead even when `meta: false` is set

---

packages/bridge/src/runtime/composables.ts

Returning `navigateTo` in `defineNuxtRouteMiddleware` causes a type error.
In the case of a bridge, Route may be returned.
Run `npx nuxi typecheck` in the following environment
https://stackblitz.com/edit/github-3fgb91-hijxwf
```log
middleware/redirect.ts:3:42 - error TS2345: Argument of type '() => Route | RawLocation | Promise<void | Route | NavigationFailure>' is not assignable to parameter of type 'RouteMiddleware'.
Type 'Route | RawLocation | Promise<void | Route | NavigationFailure>' is not assignable to type 'RouteMiddlewareReturn | Promise<RouteMiddlewareReturn>'.
Type 'Route' is not assignable to type 'RouteMiddlewareReturn | Promise<RouteMiddlewareReturn>'.
Type 'Route' is not assignable to type 'Location'.
Types of property 'name' are incompatible.
Type 'string | null | …
```

fix: allow returning `Route` from `defineNuxtRouteMiddleware`

---

.github/reproduire/needs-reproduction.md
.github/workflows/reproduire-close.yml
.github/workflows/reproduire.yml

[reproduire](https://github.com/Hebilicious/reproduire) is a great idea! I would love to introduce it to this repository.
This PR is Based on https://github.com/nuxt/nuxt/pull/22495

chore: add issue reproduction bot

---

packages/bridge/src/head.ts
packages/bridge/src/runtime/head/plugin.ts

Fixes: https://github.com/nuxt/bridge/issues/884
Nuxt Bridge does not use `VueHeadMixin`, so it is not necessary.
The error occurs when upgrading to `@unhead/vue@1.3.5` because it was using `VueHeadMixin`.

fix: remove `VueHeadMixin`

---

packages/bridge/src/module.ts

`.nuxt/tsconfig.json` is only generated for the `nuxi` command.
Composables such as `useNuxtApp` can be used without migrating to the `nuxi` command.
I want to use `.nuxt/tsconfig.json` even when using such composables without using the `nuxi` command, so that I can generate it.
(I want to reduce the pain of setting up my own aliases such as `#imports`.)

feat: generate `tsconfig.json` when not using `nuxt/cli`

---

packages/bridge/module.cjs

This mocks three missing hook methods added in newer `hookable`.

fix: mock new hookable methods

---

packages/bridge/src/runtime/app.plugin.mjs
playground/nuxt.config.ts
playground/pages/store.vue
playground/plugins/store.js
playground/store/index.js
test/bridge.test.ts

Fixes: https://github.com/nuxt/bridge/issues/928
`vue2App` is undefined in defineNuxtPlugin.
So, vue2App.$store cannot be referenced.
Because `nuxt2Context.store` can also be accessed by defineNuxtPlugin, it was changed so that it is accessed from there.
(Adding `$store` to nuxt2Context did not work.)

fix: access `$store` from nuxt2Context

---

packages/bridge/src/module.ts
packages/bridge/src/page-meta/module.ts
packages/bridge/src/page-meta/transform.ts
packages/bridge/src/runtime/page-meta/composables.ts
packages/bridge/types.d.ts
playground/layouts/custom.vue
playground/nuxt.config.ts
playground/pages/redirect.vue
playground/pages/with-layout.vue
test/bridge.test.ts

Add a module so that `definePageMeta` can also be used in Nuxt 2.
It is difficult to support other properties, so only `layout` and `middleware` will be supported first.
I have converted it as follows.
webpack
```ts
const __nuxt_page_meta = {
layout: 'test'
}
export default /*#__PURE__*/_defineComponent({
...__nuxt_page_meta,
__name: 'redirect',
setup: function setup(__props) {
return {
__sfc: true
};
}
});
```
vite
```ts
const __nuxt_page_meta = {
layout: "test"
}
const _sfc_main = /* @__PURE__ */ _defineComponent({
...__nuxt_page_meta,
__name: "redirect",
setup(__props) {
return { __sfc: true };
}
});
```

feat: add support for `definePageMeta`

---

packages/bridge/src/page-meta/transform.ts
playground/pages/redirect.vue

Fixes: https://github.com/nuxt/bridge/issues/952
When using `script setup` in Vue 2, there may be cases where the `script` tag is used in conjunction.
If `export default` is declared in `script`, then
```vue
<script setup>
definePageMeta({
middleware: ['test']
})
</script>
<script>
export default {
name: 'Test'
}
</script>
```
transformed(vite):
```js
const __default__ = {
name: "Test"
}
export default /* @__PURE__ */ _defineComponent({
...__default__,
setup(__props) {
definePageMeta({
middleware: ["test"]
});
return { __sfc: true };
}
});
```
The content of `export default` is `SpreadElement` and there is no `key`.
So I fixed it to check if there is a `key` or not.

fix: allow use with script tag

---

packages/bridge/src/app.ts
packages/bridge/src/imports/presets.ts
packages/bridge/src/runtime/app.plugin.mjs
packages/bridge/src/runtime/capi.plugin.mjs
packages/bridge/src/runtime/nitro-bridge.server.mjs
playground/middleware/redirect.ts
playground/plugins/setup.js

I would like to change to use granular imports as shown in the following improvement.
https://github.com/nuxt/nuxt/pull/23951
Refactoring of files is done in a separate PR.

perf: use granular imports for auto-importing composables

---

packages/bridge/src/page-meta/transform.ts
playground/pages/with-layout.vue

I've added a process to return if the 'init' of 'VariableDeclarator' is null, as there are cases when it can be null.
We would like to avoid `walk` what we don't need, but it is currently difficult.
For example
```ts
let value
definePageMeta({
layout: 'custom'
})
```

fix: added Handling for null init in VariableDeclarator

---

packages/bridge/src/head.ts
packages/bridge/src/imports/presets.ts

https://github.com/nuxt/bridge/issues/973
useMeta relies on useHead and assumes meta: true. Therefore, if meta: false, do not add an alias.

fix: disable `#head` alias creation when `meta: false`

---

packages/bridge/src/imports/module.ts

I want to support the imports:context hook similar to Nuxt 3. If it goes well, nuxt-vitest might also be usable.

feat: `imports:context` hook for unimport context

---

packages/bridge/src/runtime/app.plugin.mjs
packages/bridge/src/runtime/composables/asyncData.ts
playground/pages/legacy/async-data.vue
playground/pages/legacy/setup.vue
test/bridge.test.ts

Port the `useLazyAsyncData` implementation from nuxt 3.
Breaking Changes
- remove `initialCache`
- Payload cache won't be used when doing client-side navigation back to same page and fresh data will be fetched.
Feature
- support `immediate` and `deep` option
- returns `status` and `execute`

feat!: port upstream `useLazyAsyncData`

---

packages/bridge/src/runtime/app.plugin.mjs
packages/bridge/src/runtime/composables/cookie.ts
packages/bridge/src/runtime/composables/ssr.ts
packages/bridge/src/runtime/nitro/renderer.ts
playground/nuxt.config.ts
playground/pages/cookies.vue
playground/plugins/cookie.ts
test/bridge.test.ts

https://github.com/nuxt/bridge/issues/987
Port the `useCookie` implementation from nuxt 3.

feat!: port upstream `useCookie`

---

packages/bridge/src/runtime/capi.legacy.ts

#992 
I have modified the return type definition of the `defineComponent` provided by @nuxtjs/composition-api of nuxt/bridge to match the one provided by Vue.

fix: typing legacy capi `defineComponent`

---

.github/workflows/ci.yml

This fixes the release job conditional so it only checks the merge commit title and not the squashed commits in the commit body. This could incorrectly skip/prevent a release if the body contains one of the checked keywords.

ci: don't skip release based on body of commit

---

.github/workflows/needs-port-upstream.yml

The composables in nuxt/bridge are ported from nuxt 3.
So, if there are changes in nuxt 3, we need to follow the changes.
This PR notifies this repository of any modifications on the nuxt 3 side to reduce porting leaks.
Examples of Notification:
https://github.com/wattanx/repository-dispatch-target/issues/4
The notifier prepares the following workflow:
https://github.com/wattanx/repository-dispatch-owner/blob/main/.github/workflows/dispatch-update-file.yml

ci: allow notification of upstream changes

---

packages/bridge/src/runtime/app.plugin.mjs
playground/pages/async-data.vue
test/bridge.test.ts

https://github.com/nuxt/bridge/issues/1001
The error returned by useLazyAsyncData remained null even if there was an error. (if ssr: false)
Fixed to behave the same as nuxt 3.
https://stackblitz.com/edit/github-drhhpj-bd1bnm

fix: make errors returned by useLazyAsync reactive

---

packages/bridge-schema/src/config/app.ts
packages/bridge-schema/src/config/build.ts
packages/bridge-schema/src/types/loading.ts

Fixes: https://github.com/nuxt/bridge/issues/1019
Fixes: https://github.com/nuxt/bridge/issues/1016
I will correct the types for `loading`, `loadingIndicator`, `transpile` in the nuxt.config.
I would like to add type tests in a separate PR.

fix: type correction for `loading`, `loadingIndicator`, `transpile`

---

packages/bridge/module.cjs

https://github.com/nuxt/bridge/issues/1000
In the case of `hable`, since the hook does not return a function, an error is output when executing `nuxt.callHook('restart')`.
```
unsub is not a function
```
In nuxt 2.17.3, it is migrated to hookable, so maybe this support is not needed.

fix: add compatibility with `hable`

---

packages/bridge/src/module.ts
packages/bridge/src/typescript.ts
packages/bridge/types.d.ts
playground/nuxt.config.ts

Fixes: https://github.com/nuxt/bridge/issues/1063
If you add `isTSX`, you cannot use `angle-bracket syntax`.
We would like to change it to opt-in as it would be inconvenient for users who do not use `tsx`.
(If it were possible to replace `esbuild`, I would replace it.)

fix: change isTSX option to opt-in

---

packages/bridge/src/runtime/composables/asyncData.ts

Fixes: https://github.com/nuxt/bridge/issues/1081
Support `dedupe` options other than `boolean`
Also changed to log output that boolean is deprecated.
I tried to add a test similar to upstream, but I got an error `nuxt app instance unavailable` and could not introduce it.
How does upstream use nuxt instances 🤔

feat: port upstream dedupe options

---

packages/bridge/package.json
packages/bridge/src/app.ts
playground/package.json
pnpm-lock.yaml

https://github.com/nuxt/bridge/issues/1078
I would like to address this so that bridge users do not have to install hookable v5 and use `shamefully hoist`.

fix: resolve `hookable` without shamefully hoist

---

packages/bridge/src/runtime/composables/cookie.ts
packages/bridge/src/runtime/composables/ssr.ts

Fixes: https://github.com/nuxt/bridge/issues/1088
In Nuxt 3 `useRequestEvent` returns `undefined` in browser's case.

fix: in the browser, `useRequestEvent` return undefined

---

packages/bridge/src/nitro.ts
packages/bridge/src/vite/manifest.ts

I want to avoid duplicate generation of client.manifest.
In the case of a webpack production build, the manifest is generated in the following two places:
https://github.com/nuxt/bridge/blob/cffcd070e81477eef6623ac65cbe03ca4a36796e/packages/bridge/src/module.ts#L128-L130
https://github.com/nuxt/bridge/blob/cffcd070e81477eef6623ac65cbe03ca4a36796e/packages/bridge/src/nitro.ts#L241-L251

fix: prevent duplicate manifest generation

---

packages/bridge/src/page-meta/transform.ts
packages/bridge/test/page-meta.test.ts

Fixes: https://github.com/nuxt/bridge/issues/1108
If there are function calls in addition to definePageMeta, an error may occur.
(without arguments such as `const route = useRoute()`)
For `typescript` and `webpack`, since what's needed for the process is `defineComponent`, I have made corrections to only process the CallExpression of `defineComponent`.

fix: ignore CallExpression other than `defineComponent`

---

packages/bridge/src/page-meta/transform.ts
playground/pages/with-layout.vue

I would like to fix the following asynchronous functions that do not seem to be converted well when they are included.
```ts
const fn = async () => {}
```

fix: add return because the target node may not exist

---

packages/bridge/src/runtime/composables/error.ts

Fixes: https://github.com/nuxt/bridge/issues/1120
Aligns error param of Nuxt's showError and createError with H3's as in upstream.

fix: align `error` param in `showError`/`createError` with H3

---

packages/bridge/src/runtime/composables/asyncData.ts

Fixes: https://github.com/nuxt/bridge/issues/1146
Pass nuxt instance to `getCachedData`. (Port from upstream.)

feat: pass nuxt instance to `getCachedData`

---

packages/bridge/src/runtime/composables/asyncData.ts
packages/bridge/src/runtime/composables/fetch.ts
packages/bridge/src/runtime/composables/ssr.ts
playground/pages/lazy-fetch.vue
test/bridge.test.ts

Some issues can be resolved by porting.
Fixes: https://github.com/nuxt/bridge/issues/1135
Port `useLazyFetch` from nuxt upstream.
`fetchDefaults` is not supported at this time.

feat!: port upstream `useLazyFetch`

---

packages/bridge/src/runtime/composables/cookie.ts

Fixes: https://github.com/nuxt/bridge/issues/1138
I will port the changes from https://github.com/nuxt/nuxt/pull/26151

fix: watch custom `cookieRef` values deeply

---

.github/workflows/ci.yml
packages/bridge/src/vite/client.ts
packages/bridge/src/vite/manifest.ts
packages/bridge/src/vite/stub-legacy.cjs
packages/bridge/types.d.ts
playground/nuxt.config.ts

Fixes: https://github.com/nuxt/bridge/issues/1126
I want to add an option not to use `@vitejs/plugin-legacy.` 
I believe that having the option not to use `@vitejs/plugin-legacy` would make it easier to migrate to Nuxt 3 using vite mode.
(I think it will be a big change, so I decided to opt-in.)

feat: add option to not use `@vitejs/plugin-legacy`

---

packages/bridge/src/runtime/app.plugin.mjs
playground/middleware/redirect.global.ts
playground/pages/index.vue
test/bridge.test.ts

Fixes: https://github.com/nuxt/bridge/issues/1134
I think this problem is caused by taking `context` as an argument.
I believe the issue occurred because the middleware was not executed with the latest route information. Therefore, I have made a correction to use the route and from, which are callback arguments of beforeEach.

fix: use the `route` and `from` in beforeEach

---

packages/bridge/src/runtime/composables/url.ts

Fixes: https://github.com/nuxt/bridge/issues/1180
Add `opts` to `useRequestURL`.
(port from upstream)

feat: add opts param to `useRequestURL`

---

packages/bridge/src/runtime/composables/asyncData.ts

https://github.com/nuxt/nuxt/issues/25225
Pending will be removed in Nuxt 4.
I think you can help the migration by setting `pending` to `deprecated` in Nuxt Bridge.

docs: add deprecated to `pending`

---

packages/bridge/src/runtime/composables/router.ts

Port a part of `navigateTo` of upstream.
The following changes are not included
- `open` option
- Consider interrupting other middleware.
- Processing using `router.afterEach` does not seem to work with Bridge
- You can see that it doesn't work at https://github.com/nuxt/bridge/pull/1102

fix: port upstream `navigateTo`

---

packages/bridge/src/runtime/capi.legacy.ts

`defineAsyncComponent` and `proxyRefs` are supported in Vue 2.7 and can be exposed without stubs.

fix: expose `defineAsyncComponent` and `proxyRefs` at legacy runtime.

---

packages/bridge/src/runtime/composables/fetch.ts

Fixes: https://github.com/nuxt/bridge/issues/1219
The timer from the previous request may remain, which could cancel the next request. Therefore, I have made sure to clear the timer at the end of the request.
ref: https://github.com/nuxt/nuxt/pull/27308

fix: clear timeout when asyncData request finishes and aborts

---

packages/bridge/src/page-meta/transform.ts
packages/bridge/test/page-meta.test.ts

Fixes: https://github.com/nuxt/bridge/issues/1222
I expected to skip `setup` node that did not have `definePageMeta`, but I was not able to skip them, so I would like to fix that.

fix: skip node for which definePageMeta does not exist

---

packages/bridge/src/runtime/nuxt.ts

Fixes: https://github.com/nuxt/bridge/issues/1229
This is caused by a mismatch in the sigunature of `useRuntimeConfig` in Nitro and Nuxt.
This is the same way as upstream.
https://github.com/nuxt/nuxt/pull/25440

fix: match signature for nitro/nuxt `useRuntimeConfig`composables

---

packages/bridge/src/runtime/composables/router.ts
playground/pages/index.vue

resolves: https://github.com/nuxt/bridge/issues/1158
resolves: https://github.com/nuxt/bridge/issues/1255
I would like port `open` option from upstream.

feat: add `open` option in `navigateTo` helper

---

packages/bridge/src/page-meta/transform.ts
packages/bridge/test/page-meta.test.ts

In Nuxt 3 it is possible to use `definePageMeta` in the setup of defineNuxtComponent.
I would like to support the use of `definePageMeta` in `defineNuxtComponen`t in Nuxt Bridge as well as in Nuxt 3.
demo: https://stackblitz.com/edit/github-udoldr

fix: support `definePageMeta` in `defineNuxtComponent`

---

packages/bridge/src/imports/presets.ts
packages/bridge/src/runtime/composables/asyncData.ts
packages/bridge/src/runtime/composables/index.ts
playground/pages/async-data.vue
test/bridge.test.ts

https://github.com/nuxt/bridge/pull/1265
While wattanx working on the upstream port, needed `useNuxtData` to be ported,
so added it to the branch [(feat/default-data-and-error)](https://github.com/nuxt/bridge/tree/feat/default-data-and-error) he was working on.

feat: port `useNuxtData` composable

---

packages/bridge/src/vite/client.ts
packages/bridge/src/vite/server.ts

https://github.com/nuxt/bridge/issues/1295
This PR supports `import.meta.*` in vite mode.
webpack 4 does not support `import.meta`, so we need to create a plugin.

feat: support `import.meta.*` for vite

---

packages/bridge-schema/src/config/app.ts
packages/bridge/src/nitro.ts

Fixes: https://github.com/nuxt/bridge/issues/635
In nuxt 2 the option to set the cdn url is `publicPath`.
https://v2.nuxt.com/docs/configuration-glossary/configuration-build/
The `app.cdnURL` is not used directly and must be set to `publicPath`.
Also, currently `NUXT_APP_CDN_URL` is not supported and must be set to `app.cdnURL`.
```ts
export default defineNuxtConfig({
app: {
cdnURL: process.env.NUXT_APP_CDN_URL
}
})
```

fix: use legacy property `publicPath` for the assets url.

---

packages/bridge/src/runtime/composables/ssr.ts

Fixes: https://github.com/nuxt/bridge/issues/1385
I will fix the types to match upstream.
However, since Bridge does not use nitro-nightly, the import will come from nitropack.

fix: correct return type of useRequestFetch

---

.github/workflows/ci.yml
packages/bridge/src/module.ts
packages/bridge/types.d.ts
playground/nuxt.config.ts

The `resolve` option is a Webpack option that supports subpath exports.
Since this option hasn’t caused issues for a long time, I’d like to stop providing it as a configurable option.
(I was considering deprecating it, but I believe there are very few cases where it's actually being opted out of.)

fix!: remove `resolve` option

---

renovate.json

`@nuxt/kit` dropped compatibility with Nuxt 2 starting in v4, and `unhead` ended Vue 2 support in v2.
Therefore, we want to avoid bumping the major versions of these two packages.

chore: pin major versions for Nuxt and Unhead packages
