playground/nuxt.config.ts, playground/pages/runtime-config.vue, src/nitro.ts, src/runtime/composables.ts, src/runtime/nitro/renderer.ts
=> fix: add backward compatibility for new runtimeConfig

src/vite/module.ts
Now nuxt/bridge and nuxt are different projects. And vite, working in experimental mode, for bridge and nuxt may have different behavior. Accordingly, a different issue link.
=> fix: update issue link when using vite

src/auto-imports.ts, src/auto-imports/presets.ts, src/meta.ts, src/runtime/composables.ts
resolves https://github.com/nuxt/bridge/issues/350
This PR corrects a number of issues with auto-imports that were being created but not supported within the defined bridge `#app`.
=> fix: correct auto-imports

.eslintrc
=> chore: remove outdated lint rules

src/module.ts
- Allow disabling by setting `bridge: false` in nuxt.config
- Ensure `nuxt.options.bridge` is set (nuxt kit depends on this for compatibility check)
=> fix(module): resolve `bridge` top level option

module.cjs
resolves https://github.com/nuxt/bridge/issues/411
We need to initialise to an object.
=> fix: initialise bridge config to object

package.json, src/vite/manifest.ts
if nuxt route had multi-level. such as `http://a.b.c/page1/page2/page`. nuxt-bridge will throw an error.
=> fix: asset path should not be relative to page

test/bridge.test.ts, test/utils.ts
=> test: update test util to detect browser warnings

README.md
After the repository was moved, the link was no longer working
=> docs: fix link to module.ts in README

README.md
After the migration to pnpm the development environment uses pnpm to run the project.
Migration PR by @danielroe: https://github.com/nuxt/bridge/pull/598
=> docs: update package manager in readme

packages/bridge-schema/package.json, packages/bridge/package.json, packages/bridge/src/vite/client.ts, packages/bridge/src/vite/manifest.ts, packages/bridge/src/vite/server.ts, packages/bridge/src/vite/stub-vite.cjs, packages/bridge/src/vite/vite.ts, playground/nuxt.config.ts, pnpm-lock.yaml, test/bridge.test.ts
=> feat(deps): update dependency vite to v4

.github/workflows/changelogensets.yml, package.json, pnpm-lock.yaml, scripts/_utils.ts, scripts/update-changelog.ts
Add a workflow that automatically creates release PRs.
Implemented with reference to https://github.com/nuxt/nuxt/blob/main/.github/workflows/changelogensets.yml.
=> ci: add workflow to automatically create release PR

packages/bridge/src/app.ts, packages/bridge/src/global-middleware-template.ts, packages/bridge/src/runtime/app.plugin.mjs, packages/bridge/src/utils/names.ts, playground/middleware/redirect.global.ts, playground/middleware/redirect.ts, test/bridge.test.ts
Nuxt Bridge will also support the `Global Middleware` of Nuxt 3.
This will make it easier to proceed with the migration of the router middleware.
=> feat: add support for global middleware

packages/bridge/src/webpack/manifest.ts
I will support `build:manifest` hook for webpack.
This should also enable disabling prefetch for dynamic imports.
=> feat: support `build:manifest` hook for webpack

.github/workflows/needs-port-upstream.yml
I made a mistake with the key name of the payload I received from upstream. 🙈 
Creating the issue went well!
https://github.com/nuxt/bridge/issues/1021
=> ci: fix client_payload key

packages/bridge/src/runtime/app.plugin.mjs
Fixes: https://github.com/nuxt/bridge/issues/1036
I want to add an option to the `vueApp.use` argument.
=> fix: add an option to the argument

scripts/update-changelog.ts
Remove `prerelease` to support major releases.
=> ci: update changelog with new version (remove prerelease)

packages/bridge/src/module.ts, packages/bridge/src/runtime/head/plugins/unhead.ts, packages/bridge/src/runtime/nitro/renderer.ts
Fixes: https://github.com/nuxt/bridge/issues/1051
A critical tag was not inserted in the html template.
=> fix: Inject head into template in spa renderer

packages/bridge/package.json
Ensures versions stay in sync.
=> chore: use workspace version of bridge-schema

packages/bridge/package.json, packages/bridge/src/page-meta/transform.ts, packages/bridge/test/page-meta.test.ts, pnpm-lock.yaml
Fixes: https://github.com/nuxt/bridge/issues/1103
When using `script` and `script setup` together in webpack, the structure seemed to be different from vite.
I fixed searching for child nodes to get the expected node.
vite
```ts
const __default__ = {
name: "RedirectPage"
};
const _sfc_main = /* @__PURE__ */ _defineComponent({
...__default__,
setup(__props) {
definePageMeta({
middleware: ["redirect"]
})
return { __sfc: true };
}
});
```
webpack
```ts
var __default__ = {
name: 'RedirectPage'
};
export default /*#__PURE__*/_defineComponent(_objectSpread(_objectSpread({}, __default__), {}, {
setup: function setup(__props) {
definePageMeta({
middleware: ['redirect']
});
return {
__sfc: true
};
}
}));
```
=> fix: support the use of `script setup` and `script` together in webpack

packages/bridge/src/imports/presets.ts, packages/bridge/src/runtime/composables/url.ts, playground/pages/url.vue, test/bridge.test.ts
Port upstream's `useRequestURL` composables to Nuxt Bridge as well.
(I'm wondering if I should add `@since`.)
=> feat: port `useRequestURL` from upstream

packages/bridge/src/runtime/composables/cookie.ts
Fixes: https://github.com/nuxt/bridge/issues/1151
Port the handling of BroadcastChannel creating failure.
(Cookie Store does not support.)
=> fix: port the handling of BroadcastChannel creating failure

packages/bridge/src/runtime/composables/asyncData.ts
Fixes: https://github.com/nuxt/bridge/issues/1171
We would like to port https://github.com/nuxt/nuxt/pull/26554
=> perf: unsubscribe from watch when scope is disposed

packages/bridge/src/runtime/composables/asyncData.ts
Fixes: https://github.com/nuxt/bridge/issues/1140
This will port the async transform from upstream.
ref: https://github.com/nuxt/nuxt/pull/26154
=> feat: support async transforms

packages/bridge/src/runtime/composables/asyncData.ts
Related to [#26820](https://github.com/nuxt/nuxt/issues/26820), same issue will be here after 3.2.0 release
Exact same as https://github.com/nuxt/nuxt/pull/26821
Fixes performance degradation inproduced in https://github.com/nuxt/bridge/pull/1172
=> perf(nuxt): unsubscribe from asyncData watch when component is unmounted

packages/bridge/src/imports/presets.ts, packages/bridge/src/runtime/composables/asyncData.ts, packages/bridge/src/runtime/composables/index.ts, packages/bridge/src/utils/toArray.ts, playground/pages/async-data.vue, playground/server/api/hello.ts, test/bridge.test.ts
Fixes: https://github.com/nuxt/bridge/issues/1148
Port `clear` function and `clearNuxtData` util from upstream.
ref: https://github.com/nuxt/nuxt/pull/26259
=> feat: port `clear` function and `clearNuxtData` util from upstream

packages/bridge/test/page-meta.test.ts
page-meta test inputs used transformed code.
So it is difficult to know the code before transformation.
In this PR, I have enabled writing tests using original code like script setup as input
=> test: refactor page-meta test

packages/bridge/src/runtime/composables/asyncData.ts
Fixes: https://github.com/nuxt/bridge/issues/1251
Fixed to update flag if defined as same as upstream.
=> fix: flag async data promise as cancelled only if defined

packages/bridge/src/app.ts
Fixes: https://github.com/nuxt/bridge/issues/1281
`cookie-es` now also needs transpile.
=> fix: add `cookie-es` to transpiles

packages/bridge/src/runtime/nitro/renderer.ts
Fixes: https://github.com/nuxt/bridge/issues/1287
For vite-node, the manifest needs to be updated after rendering.
https://github.com/nuxt/framework/pull/5017
=> fix: fouc on dev ssr

packages/bridge/src/vite/manifest.ts
seems we weren't calling this hook unless using the webpack builder
=> fix(bridge): call `build:manifest` for vite builder

packages/bridge/src/runtime/composables/asyncData.ts, packages/bridge/src/runtime/composables/error.ts
Fixes: https://github.com/nuxt/bridge/issues/1494
In this PR, we port the following fix to Bridge.
- https://github.com/nuxt/nuxt/pull/31676
- https://github.com/nuxt/nuxt/pull/24396
=> fix: ensure `error` in `useAsyncData` has correct type

packages/bridge/src/runtime/composables/error.ts
Fixes: https://github.com/nuxt/bridge/issues/1616
port upstream Nuxt 3 error composable improvements to Bridge.
=> feat: port upstream error composable improvements
